Getting there

diff --git a/bin/cron-job b/bin/cron-job
--- a/bin/cron-job
+++ b/bin/cron-job
@@ -1,18 +1,23 @@
 #! /bin/bash
 # (c) Copyright 2020 - James Stevens
 
+
 if test -z "${base}" -o -z "${icann_root_dns}"
 	then
 		echo "ERROR: running config is incomplete"
 		exit 1
 	fi
 
+set -x
+
 digcmd="dig +nocmd +nocomments +nostats"
+
 
 rm -f ${base}/tmp/*
 
+
 icann_old_soa=0
-newest_icann=$(ls ${base}/zones/icann* | tail -1)
+newest_icann=$(ls ${base}/zones/icann* 2>/dev/null | tail -1)
 if test "${newest_icann}" -a -f "${newest_icann}"
 	then
 		icann_old_soa="$(awk '{ if (($1==".")&&($4=="SOA")) { print $7; exit(0) } }' ${newest_icann})"
@@ -24,20 +29,17 @@ resign="N"
 
 now="$(date +%Y%m%d_%H%M%S)"
 
-set -x
 
 if test ${icann_now_soa} -gt ${icann_old_soa}
 	then
 		tmp=$(mktemp ${base}/tmp/icann_XXXXXX)
 		${digcmd} @${icann_root_dns} . axfr | tr $'\t' ' ' | awk 'BEGIN {
-			block["RRSIG"] = "Y"
-			block["NSEC"] = "Y"
-			block["NSEC3"] = "Y"
-			block["DNSKEY"] = "Y"
-			block["NSEC3PARAM"] = "Y"
-			} { if (block[$4] != "Y") print }' > ${tmp}
+			block["RRSIG"] = "Y"; block["NSEC"] = "Y";
+			block["NSEC3"] = "Y"; block["DNSKEY"] = "Y";
+			block["NSEC3PARAM"] = "Y"; } 
+			{ if (block[$4] != "Y") print }' > ${tmp}
 
-		if test -z "${newest_icann}" || cmp ${tmp} ${newest_icann}
+		if test -z "${newest_icann}" || ! cmp ${tmp} ${newest_icann}
 			then
 				newest_icann="${base}/zones/icann_${now}.txt"
 				mv ${tmp} ${newest_icann}
@@ -49,5 +51,87 @@ if test ${icann_now_soa} -gt ${icann_old_soa}
 	fi
 
 
-ncpu=$(lscpu | awk '/^CPU\(s\)/ { print $NF }')
-salt=$(hexdump -n 5 -e '4/4 "%02X" 1 "\n"' /dev/random | tr -d ' ')
+
+
+handshake_old_soa=0
+newest_handshake=$(ls ${base}/zones/handshake* 2>/dev/null | tail -1)
+if test "${newest_handshake}" -a -f "${newest_handshake}"
+	then
+		handshake_old_soa="$(awk '{ if (($1==".")&&($4=="SOA")) { print $7; exit(0) } }' ${newest_handshake})"
+	fi
+
+handshake_now_soa="$(${digcmd} +norec +short @${handshake_root_dns} . soa | awk '{ print $3 }')"
+
+
+if test ${handshake_now_soa} -gt ${handshake_old_soa}
+	then
+		tmp=$(mktemp ${base}/tmp/handshake_XXXXXX)
+		{
+		echo ". 86400  IN SOA . . ${handshake_now_soa} 1800 900 604800 86400"
+		echo ". 518400 IN NS ."
+		echo ". 518400 IN A 127.0.0.1"
+		} > "${tmp}~"
+
+		${hsd_rpc} dumpzone ${tmp}
+
+		x=0
+		while ! test -s ${tmp}
+			do
+				x=$[${x}+1]
+				if test ${x} -gt 180
+					then
+						rm -f ${tmp}
+						echo "ERROR: RPC dumpzone to ${tmp} Failed"
+						exit 1
+					fi
+				sleep 1
+			done
+
+
+		if test -z "${newest_handshake}" || ! cmp ${tmp} ${newest_handshake}
+			then
+				newest_handshake="${base}/zones/handshake_${now}.txt"
+				mv ${tmp} ${newest_handshake}
+				resign="Y"
+			else
+				rm -f ${tmp}
+				echo "No change to ICANN - ${handshake_now_soa}"
+			fi
+	fi
+
+
+
+
+
+
+# ncpu=$(lscpu | awk '/^CPU\(s\)/ { print $NF }')
+# salt=$(hexdump -n 5 -e '4/4 "%02X" 1 "\n"' /dev/random | tr -d ' ')
+
+
+
+echo "----> ${resign} ${newest_handshake} ${newest_icann}"
+
+
+if ! test "${priority_icann}" = "Y"
+	then
+		one="${newest_handshake}"; file="${newest_icann}"
+	else
+		file="${newest_handshake}"; one="${newest_icann}"
+	fi
+
+{
+grep '^. ' ${newest_handshake}
+grep -v '^. ' ${one}
+awk 'BEGIN {
+	one="'"${one}"'"
+	dups="'"${base}"'/tmp/dups"
+
+	while((getline < one)==1) have_one[$1]="Y"
+	have_one["."] = "N"
+	}
+	{
+		if (have_one[$1]!="Y") print;
+		else print $0 > dups
+	}' ${file}
+
+} > ${base}/tmp/both
