Mostly complete, should work

diff --git a/bin/handshake-bridge-cronjob b/bin/handshake-bridge-cronjob
--- a/bin/handshake-bridge-cronjob
+++ b/bin/handshake-bridge-cronjob
@@ -1,8 +1,11 @@
 #! /bin/bash
 # (c) Copyright 2020 - James Stevens
 
-set -x 
+pipecmd="logger -i -t handshake-bridge-cron"
+if test "${1}" = "startup"; then pipecmd="cat"; fi
 
+
+{
 base="$(dirname $(dirname ${0}))"
 if test "${base}" = "."; then base="$(pwd)"; fi
 
@@ -14,6 +17,8 @@ if test -z "${base}"
 
 . ${base}/config
 
+icann_root="${bind_local_prefix}.3"
+if test "${1}" = "startup"; then icann_root="f.root-servers.net."; fi
 
 
 function handshake_header()
@@ -36,9 +41,10 @@ if test "${newest_icann}" -a -f "${newest_icann}"
 		icann_old_soa="$(awk '{ if (($1==".")&&($4=="SOA")) { print $7; exit(0) } }' ${newest_icann})"
 	fi
 
-icann_now_soa="$(${digcmd} +norec +short @${icann_root_dns} . soa | awk '{ print $3 }')"
+icann_now_soa="$(${digcmd} +norec +short @${icann_root} . soa | awk '{ print $3 }')"
 
 resign="N"
+if test "${1}" = "force"; then resign="Y"; fi
 
 now="$(date +%Y%m%d_%H%M%S)"
 
@@ -46,7 +52,7 @@ now="$(date +%Y%m%d_%H%M%S)"
 if test ${icann_now_soa} -gt ${icann_old_soa}
 	then
 		tmp=$(mktemp ${base}/tmp/icann_XXXXXX)
-		${digcmd} @${icann_root_dns} . axfr | tr $'\t' ' ' | awk 'BEGIN {
+		${digcmd} @${icann_root} . axfr | tr $'\t' ' ' | awk 'BEGIN {
 			block["RRSIG"] = "Y"; block["NSEC"] = "Y";
 			block["NSEC3"] = "Y"; block["DNSKEY"] = "Y";
 			block["NSEC3PARAM"] = "Y"; } 
@@ -69,7 +75,7 @@ if test "${newest_handshake}" -a -f "${newest_handshake}"
 		handshake_old_soa="$(awk '{ if (($1==".")&&($4=="SOA")) { print $7; exit(0) } }' ${newest_handshake})"
 	fi
 
-handshake_now_soa="$(${digcmd} +norec +short @${handshake_root_dns} . soa | awk '{ print $3 }')"
+handshake_now_soa="$(${digcmd} +norec +short @${hsd_server_addr} . soa | awk '{ print $3 }')"
 
 
 if test ${handshake_now_soa} -gt ${handshake_old_soa}
@@ -77,37 +83,36 @@ if test ${handshake_now_soa} -gt ${handshake_old_soa}
 		tmp=$(mktemp ${base}/tmp/handshake_XXXXXX)
 		handshake_header "${handshake_now_soa}" > "${tmp}~"
 
-		${hsd_rpc} dumpzone ${tmp}
+		${hsd_rpc} dumpzone ${tmp} > /dev/null 2>&1
 
 		x=0
 		while ! test -s ${tmp}
 			do
+				echo -n "."
 				x=$[${x}+1]
 				if test ${x} -gt 180
 					then
-						rm -f ${tmp}
+						rm -f tmp/*
+						echo ""
 						echo "ERROR: RPC dumpzone to ${tmp} Failed"
 						exit 1
 					fi
 				sleep 1
 			done
 
+		echo ""
 		newest_handshake="${base}/zones/handshake_${now}.txt"
 		mv ${tmp} ${newest_handshake}
 		resign="Y"
 	fi
 
 
-
-
-
-
-# ncpu=$(lscpu | awk '/^CPU\(s\)/ { print $NF }')
-# salt=$(hexdump -n 5 -e '4/4 "%02X" 1 "\n"' /dev/random | tr -d ' ')
-
-
-
-echo "----> ${resign} ${newest_handshake} ${newest_icann}"
+# echo "----> ${resign} ${newest_handshake} ${newest_icann}"
+if ! test "${resign}" = "Y"
+	then
+		echo "Resigning not required"
+		exit 0
+	fi
 
 
 if test "${priority_icann}" = "Y"
@@ -124,7 +129,7 @@ if test "${priority_icann}" = "Y"
 
 
 {
-handshake_header "${handshake_now_soa}"
+handshake_header "$(date +%s)"
 
 grep -v '^. ' ${keep}
 
@@ -151,15 +156,33 @@ if test -s tmp/dups
 		rm -f tmp/dups
 	fi
 
+if ! named-checkzone -i local-sibling -k ignore . tmp/ROOT
+	then
+		echo "ERROR: Merged ROOT zone failed validation check"
+		exit 1
+	fi
+
 
 . ${base}/etc/nsec3.salt
 
+start="$(awk 'BEGIN { x=systime(); srand(x/604800*13); x = int(x / 604800) * 604800; x += int(rand() * 86400); print strftime("%Y%m%d%H%M%S",x); }')"
+
 cd ${base}/tmp
-dnssec-signzone -o . -t -R -S -A -H 5 -3 ${nsec3_salt} -K ../keys ROOT
+dnssec-signzone -s ${start} -o . -t -R -S -A -H 5 -3 ${nsec3_salt} -K ../keys ROOT
 cd ${base}
 
-
-cp tmp/ROOT.signed named/zones/
-rndc -c ${base}/etc/rndc.conf reload . in root
+if ! named-checkzone -i local-sibling -k ignore . tmp/ROOT.signed
+	then
+		echo "ERROR: Merged & Signed ROOT zone failed validation check"
+		exit 1
+	else
+		cp tmp/ROOT.signed named/zones/
+		if ! test "${1}" = "startup"
+			then
+				rndc -c ${base}/etc/rndc.conf reload . in root
+			fi
+	fi
 
 rm tmp/*
+
+} 2>&1 | ${pipecmd}
diff --git a/bin/set-up b/bin/set-up
--- a/bin/set-up
+++ b/bin/set-up
@@ -1,30 +1,37 @@
 #! /bin/bash
 # (c) Copyright 2020 - James Stevens
 
+base="$(dirname $(dirname ${0}))"
+if test "${base}" = "."; then base="$(pwd)"; fi
 
-base="$(pwd)"
 . ${base}/config
 
-sudo umount ${base}/named/dev/log 2>/dev/null
+sudo=""
+if ! test $(id -u) = 0
+	then	
+		sudo="sudo"
+	fi
+
+${sudo} umount ${base}/named/dev/log 2>/dev/null
+${sudo} killall -q named-handshake-bridge
 
 # ncpu=$(lscpu | awk '/^CPU\(s\)/ { print $NF }')
 
 dirs="zones archive keys tmp named etc"
-rm -rf ${dirs}
+${sudo} rm -rf ${dirs}
 
 mkdir ${dirs}
 mkdir named/dev named/etc named/var named/var/named named/zones
 
 chmod 700 keys
-sudo chown nobody: named/var/named
 
-sudo cp -a /dev/zero /dev/random /dev/urandom /dev/null named/dev
+chmod 770 named/zones
+${sudo} chgrp $(id -g nobody) named/zones
+${sudo} chown nobody: named/var/named
+
+${sudo} cp -a /dev/zero /dev/random /dev/urandom /dev/null named/dev
 touch named/dev/log
-sudo mount -o bind /dev/log ${base}/named/dev/log
-
-rndc-confgen -s ${bind_local_addr} > etc/rndc.conf
-awk '/^#/&&!/named.conf/&&!/of rndc.conf/ { print substr($0,3) }' etc/rndc.conf > named/etc/rndc.inc
-chmod 444 named/etc/rndc.inc
+${sudo} mount -o bind /dev/log ${base}/named/dev/log
 
 
 dnssec-keygen -K keys -a "${signing_algorithm}" -n ZONE -r /dev/urandom -L 86400 -f KSK -3 .
@@ -32,22 +39,76 @@ dnssec-keygen -K keys -a "${signing_algorithm}" -n ZONE -r /dev/urandom -L 86400
 
 
 # `bind` is a fussy bitch, it won't listen on an address unless its assigned :(
-for addr in ${bind_loop_addr} ${bind_local_addr}
+for x in 1 2 3 5
 do
+	addr="${bind_local_prefix}.${x}"
 	if ! ip addr show lo | grep -q "inet ${addr}/"
 		then
-			sudo ip addr add ${addr}/8 dev lo
+			${sudo} ip addr add ${addr}/8 dev lo
 		fi
 done
 
 
-awk '/ 257 / { 
-	$8="\"" _ $8; 
+awk '/ 257 / { $8="\"" _ $8; 
 	printf "trusted-keys {\n\t\".\" %s\";\n};\n",substr($0,index($0," 257 ")) 
 	}' keys/*.key > named/etc/trusted-keys.inc
 
 chmod 444 named/etc/trusted-keys.inc
 
-salt=$(hexdump -n 5 -e '4/4 "%02X" 1 "\n"' /dev/random | tr -d ' ')
+salt="$(dd if=/dev/urandom count=6 bs=1 2>/dev/null | hexdump | awk '{ print $2 $3 $4 }')"
 echo "nsec3_salt='${salt}'" > etc/nsec3.salt
+chmod 444 etc/nsec3.salt
 
+
+sed "s/MERGED_ADDR/${bind_local_prefix}.5/g" named.conf > named/etc/named.conf
+chmod 444 named/etc/named.conf
+
+
+merged_addr="${bind_local_prefix}.5"
+
+{
+echo "acl merged_acl    { ${merged_addr}; };"
+echo "acl recursive_acl { ${bind_local_prefix}.1; ${bind_recusive_addr}; };"
+echo "acl slave_acl     { ${bind_local_prefix}.2; ${bind_slave_addr}; };"
+echo "acl mirror_acl    { ${bind_local_prefix}.3; ${bind_mirror_addr}; };"
+echo ""
+echo "masters merged_masters    { ${merged_addr}; };"
+echo "masters recursive_masters { ${bind_local_prefix}.1; ${bind_recusive_addr}; };"
+echo "masters slave_masters     { ${bind_local_prefix}.2; ${bind_slave_addr}; };"
+echo "masters mirror_masters    { ${bind_local_prefix}.3; ${bind_mirror_addr}; };"
+} > named/etc/addrs.inc
+chmod 444 named/etc/addrs.inc
+
+
+rndc-confgen -s ${merged_addr} > etc/rndc.conf
+awk '/^#/&&!/named.conf/&&!/of rndc.conf/ { 
+	if ($2=="allow") $4="127.0.0.0/8;"
+	print substr($0,3) 
+	}' etc/rndc.conf > named/etc/rndc.inc
+chmod 444 named/etc/rndc.inc
+
+
+if ! ${base}/bin/handshake-bridge-cronjob startup
+	then
+		echo "ERROR: Failed to create merged ROOT zone"
+		exit 1
+	fi
+
+
+ln -fns $(which named) ${base}/bin/named-handshake-bridge
+
+if ! ${sudo} named-checkconf -t /opt/handshake-bridge/named
+	then
+		echo "ERROR: named config failed validation"
+		exit 1
+	fi
+
+${sudo} ${base}/bin/named-handshake-bridge -t /opt/handshake-bridge/named/ -u nobody
+
+tmp="$(mktemp)"
+{
+crontab -l | grep -v handshake-bridge-cronjob
+echo "*/15 * * * * ${base}/bin/handshake-bridge-cronjob"
+} > ${tmp}
+crontab ${tmp}
+rm -f ${tmp}
