fixes for alpine/busybox, more integrity checks

diff --git a/bin/handshake-bridge-cronjob b/bin/handshake-bridge-cronjob
--- a/bin/handshake-bridge-cronjob
+++ b/bin/handshake-bridge-cronjob
@@ -3,7 +3,7 @@
 
 export PATH=/bin:/sbin:/usr/bin:/usr/sbin
 
-pipecmd="logger -i -t handshake-bridge-cron"
+pipecmd="logger -t handshake-bridge-cron"
 if test "${1}" || tty -s ; then pipecmd="cat"; fi
 
 
@@ -32,26 +32,41 @@ if test "${1}" = "startup"; then icann_root="f.root-servers.net."; fi
 function handshake_header()
 {
 	echo ". 3600  IN SOA . . ${1} 1800 900 604800 86400"
-	echo ". 518400 IN NS ."
-	echo ". 518400 IN A 127.0.0.1"
+	echo ". 518400 IN NS a-root-names-servers-net."
+	echo ". 518400 IN NS b-root-names-servers-net."
+	echo "a-root-names-servers-net. 86400 in a 127.9.0.5"
+	echo "b-root-names-servers-net. 86400 in a 127.9.0.2"
 }
 
 
 digcmd="dig +nocmd +nocomments +nostats"
 
-rm -f ${base}/tmp/*
+rm -fv ${base}/tmp/*
 
 
 icann_old_soa=0
 newest_icann=$(ls ${base}/zones/icann* 2>/dev/null | tail -1)
-if test "${newest_icann}" -a -f "${newest_icann}"
+if test "${newest_icann}" -a ! -s "${newest_icann}"
+	then
+		echo "ERROR: ICANN file is empty"
+		rm -vf "${newest_icann}"
+		exit 1
+	fi
+	
+if test "${newest_icann}" -a -s "${newest_icann}"
 	then
 		icann_old_soa="$(awk '{ if (($1==".")&&($4=="SOA")) { print int($7)+0; exit(0) } }' ${newest_icann})"
+		if test -z "${icann_old_soa}" -o "${icann_old_soa}" -lt 1
+			then
+				echo "ERROR: Failed to read old SOA for ICANN"
+				rm -fv "${newest_icann}"
+				exit 1
+			fi
 	fi
 
 icann_now_soa="$(${digcmd} +norec +short @${icann_root} . soa | awk '{ print $3 }')"
 
-if test -z "${icann_now_soa}" -o -z "${icann_old_soa}" -o "${icann_now_soa}" -lt 1
+if test -z "${icann_now_soa}" -o "${icann_now_soa}" -lt 1
 	then
 		echo "ERROR: Failed to query for ICANN SOA Serial"
 		exit 1
@@ -75,11 +90,27 @@ if test "${icann_now_soa}" -gt "${icann_old_soa}"
 			gsub("\t"," ",x);
 			while(index(x,"  ")) gsub("  "," ",x);
 			print x }' | sort > ${tmp}
+		
+		{
+		if ! named-checkzone -i local-sibling -k ignore . ${tmp}
+			then
+				echo "ERROR: ICANN file failed checks"
+				rm -vf ${tmp}
+				exit 1
+			fi
+		} | grep -v 'has no address records'
+
+		if ! test -s ${tmp}
+			then
+				echo "ERROR: ICANN axfr failed"
+				rm -fv ${tmp}
+				exit 1
+			fi
 
 		if ! dnssec-verify -o . ${tmp}
 			then
 				echo "ERROR: ICANN ROOT zone failed DNSSEC verification"
-				rm -f ${base}/tmp/*
+				rm -fv ${base}/tmp/*
 				exit 1
 			fi
 
@@ -98,17 +129,29 @@ if test "${icann_now_soa}" -gt "${icann_old_soa}"
 
 
 
-
 handshake_old_soa=0
 newest_handshake=$(ls ${base}/zones/handshake* 2>/dev/null | tail -1)
-if test "${newest_handshake}" -a -f "${newest_handshake}"
+if test "${newest_handshake}" -a ! -s "${newest_handshake}"
+	then
+		echo "ERROR: Handshake newest file is empty"
+		rm -vf "${newest_icann}"
+		exit 1
+	fi
+	
+if test "${newest_handshake}" -a -s "${newest_handshake}"
 	then
 		handshake_old_soa="$(awk '{ if (($1==".")&&($4=="SOA")) { print int($7)+0; exit(0) } }' ${newest_handshake})"
+		if test -z "${handshake_old_soa}" -o "${handshake_old_soa}" -lt 1
+			then
+				echo "ERROR: Handshake ${newest_handshake} has not SOA"
+				rm -vf "${newest_handshake}"
+				exit 1
+			fi
 	fi
 
 handshake_now_soa="$(${digcmd} +norec +short @${hsd_server_addr} . soa | awk '{ print $3 }')"
 
-if test -z "${handshake_now_soa}" -o -z "${handshake_old_soa}" -o "${handshake_now_soa}" -lt 1
+if test -z "${handshake_now_soa}" -o "${handshake_now_soa}" -lt 1
 	then
 		echo "ERROR: Failed to query for Handshake SOA Serial"
 		exit 1
@@ -130,7 +173,7 @@ if test "${handshake_now_soa}" -gt "${handshake_old_soa}"
 				x=$[${x}+1]
 				if test ${x} -gt 180
 					then
-						rm -f ${base}/tmp/*
+						rm -fv ${base}/tmp/*
 						echo ""
 						echo "ERROR: RPC dumpzone to ${tmp} Failed"
 						rm -vf ${changed_files}
@@ -140,6 +183,15 @@ if test "${handshake_now_soa}" -gt "${handshake_old_soa}"
 			done
 
 		echo ""
+		{
+		if ! named-checkzone -i local-sibling -k ignore . ${tmp}
+			then
+				echo "ERROR: Handshake dump file ${tmp} failed check"
+				rm -fv ${tmp}
+				exit 1
+			fi
+		} | grep -v 'has no address records'
+			
 		newest_handshake="${base}/zones/handshake_${now}.txt"
 		mv ${tmp} ${newest_handshake}
 		changed_files="${changed_files} ${newest_handshake}"
@@ -195,15 +247,17 @@ awk 'BEGIN {
 if test -s ${base}/tmp/dups
 	then
 		awk '{ print "'"${dups}"' Duplicate removed:",$0 }' ${base}/tmp/dups
-		rm -f ${base}/tmp/dups
+		rm -fv ${base}/tmp/dups
 	fi
 
-if ! named-checkzone -i local-sibling -k ignore . ${base}/tmp/ROOT
+{
+if ! named-checkzone -i local-sibling -k ignore . ${base}/tmp/ROOT 
 	then
 		echo "ERROR: Merged ROOT zone failed validation check"
 		rm -vf ${changed_files}
 		exit 1
 	fi
+} | grep -v 'has no address records'
 
 
 . ${base}/etc/nsec3.salt
@@ -219,6 +273,7 @@ if ! dnssec-signzone -s ${start} -o . -t -P -R -S -A -H 5 -3 ${nsec3_salt} -K ${
 mv dsset-. ${base}
 cd ${base}
 
+{
 if ! named-checkzone -i local-sibling -k ignore . ${base}/tmp/ROOT.signed
 	then
 		echo "ERROR: Merged & Signed ROOT zone failed validation check"
@@ -231,6 +286,7 @@ if ! named-checkzone -i local-sibling -k ignore . ${base}/tmp/ROOT.signed
 				rndc -c ${base}/etc/rndc.conf reload . in root
 			fi
 	fi
+} | grep -v 'has no address records'
 
 rm ${base}/tmp/*
 
@@ -241,13 +297,13 @@ icann_files="$(ls -t icann_* | tail -n +${keep_zones_files})"
 
 if test "${handshake_files}${icann_files}"
 	then
-		mv -v ${handshake_files} ${icann_files} ${base}/archive
+		mv ${handshake_files} ${icann_files} ${base}/archive
 		cd ${base}/archive
-		xz -v ${handshake_files} ${icann_files}
+		xz ${handshake_files} ${icann_files}
 	fi
 cd ${base}
 
-find ${base}/archive/ -type f -mtime +30 -printf "Removing %p\n" -delete
+find ${base}/archive/ -type f -mtime +30 -delete -print | awk '{ print "Removing",$0 }'
 
 echo "Resign Finished"
 } 2>&1 | ${pipecmd}
